### ISSUE TITLE
Error running 'uncalled map'

### ISSUE THREAD

**Issue by jkzrich** [skovaka/UNCALLED#10]
Hello,

I've installed UNCALLED and am attempting to run through the example. Indexing via BWA and UNCALLED appeared to run normally, however, I am getting an error when trying to map. This is the command used:

    uncalled map -t 8 example_ref.fa fast5_filename.txt > uncalled_out.paf

This is the error that I am receiving:

    Loading fast5s
    Mapping
    HDF5-DIAG: Error detected in HDF5 (1.8.21) thread 0:
    #000: H5D.c line 356 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
    #001: H5Gloc.c line 428 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
    #002: H5Gtraverse.c line 859 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
    #003: H5Gtraverse.c line 639 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
    #004: H5Gloc.c line 383 in H5G_loc_find_cb(): object 'Signal' doesn't exist
    major: Symbol table
    minor: Object not found
    Traceback (most recent call last):
    File "/usr/local/bin/uncalled", line 436, in <module>
    map_cmd(args)
    File "/usr/local/bin/uncalled", line 247, in map_cmd
    for p in mapper.update():
    RuntimeError: /Raw/Reads/Signal: error in H5Dopen
    terminate called without an active exception
    Aborted

Any ideas? Thanks, I really appreciate it!

**Comment by skovaka** [comment]
Sorry about that! The recent update broke how I loaded the old version of single fast5s, which the example still uses. I just fixed and updated the repository. Thanks for letting me know.

**Comment by jkzrich** [comment]
Hello, 

Thanks for the reply! I tried to map the example data again after the update, but I'm still receiving the same error as before. Do you think that there may be a problem with my HDF5 installation? Thanks again, I appreciate it!

Jon

**Comment by jkzrich** [comment]
Thank you! Everything seems to be running fine now.

Jon
